version: '3'
services:

  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: hellokoding
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build:
      context: target # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: ../Dockerfile
    working_dir: /etutoring
    volumes:
      - ./etutoring:/etutoring
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql